### ISSUE TITLE
Return the train-test splits from a task

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/python#20]
Tasks currently have a get_train_and_test_set method to return the train and test set for a specific CV repeat/fold. However, I see no way to get the number of repeats and folds? Can we please either:
- add functions to return the CV specs (i.e. the number of folds and repeats)
- return the whole set of train-test split as a numpy array (tensor of repeat x fold x splits)?

**Comment by mfeurer** [comment]
Hm, ideally we would like an iterator regardless of the resampling strategy, right? Then we could do something like:

    for train_indices, test_indices in task.iter_splits():
        ...

Additionaly to that, finding the number of folds and repeats seems like a good idea.

**Comment by joaquinvanschoren** [comment]
Yes, that sounds even better!

**Comment by mfeurer** [comment]
I just created a new feature branch and added this feature with commit 9329070

@PG-TUe can you please check whether this helps you? I can then merge it to develop and you can rebase your branch.

**Comment by PG-TUe** [comment]
Will try today/tomorrow (most likely tomorrow), and report back. Thanks.

**Comment by PG-TUe** [comment]
I've been looking at the code, and while the (lazy) iteration over repeats and folds works well, there is one issue. As far as I can tell, there is still no way to find the number of repeats and folds from just the task object. This in turn gives issues, because using task.iterate_splits(), you don't know when the next split is actually a new fold of the same repeat, or a new fold of a new repeat.

So, the new code is fine, but additionally we would need a way to retrieve the number of repeats and folds from the task directly, before it is of any use.

Of course, I might have missed something, and perhaps it is possible to see the number of repeats and folds without accessing the split object. If so, please point me in the right direction ;)

**Comment by PG-TUe** [comment]
I got around to doing it myself, it can now be used in your old implementation by calling:
```
task.iterate_all_splits()
```
However, to more easily use repeats and folds, you can now also do:
```
for rep in task.iterate_repeats():
    for fold in rep:
        train, test = fold
```
Of course, you can instead use ```for train, test in rep``` directly as well.

**Comment by mfeurer** [comment]
Looks great. Can this be closed?

**Comment by PG-TUe** [comment]
In that case, yes. Issue closed.
